// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "dfa7ccab-a658-4d85-b428-29553ebbbfae");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1667301915);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1667301932);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{e4e95fc9-6ae0-4567-9ff4-95527e506cec}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1667301907);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{76fb8b84-2a96-4d62-ac14-2727eaeadeb5}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1667301909);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1667301935401");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1667323535401");
user_pref("browser.search.region", "SE");
user_pref("browser.search.separatePrivateDefault.urlbarResult.enabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20221025212237");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1667301932");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20221025212237");
user_pref("browser.startup.homepage_override.mstone", "106.0.2");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_14\",\"url\":\"https://www.mozilla.org/firefox/welcome/14\",\"expire\":1668470400000}");
user_pref("browser.startup.lastColdStartupCheck", 1667301932);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1667301908722");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "106.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "SE");
user_pref("dom.push.userAgentID", "fdb39c1d4edf4ecba40e39e408893296");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221025212237");
user_pref("extensions.lastAppVersion", "106.0.2");
user_pref("extensions.lastPlatformVersion", "106.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"80eba513-9edd-4321-bd57-13a77cf85584\",\"pictureinpicture@mozilla.org\":\"8719aeb8-1155-4b51-8ff4-c0adef1ab957\",\"screenshots@mozilla.org\":\"53b694d4-e64e-4c9e-a935-35e68cadc861\",\"webcompat-reporter@mozilla.org\":\"8779c868-b56b-401f-951c-5ad915aa4338\",\"webcompat@mozilla.org\":\"71f75d4d-2a96-4f34-bbff-0a1bedff823e\",\"default-theme@mozilla.org\":\"27538cae-be71-4993-82cc-5f4f0615aac8\",\"addons-search-detection@mozilla.com\":\"da6df642-23fa-4618-b541-8be460639ed4\",\"google@search.mozilla.org\":\"ab8c0574-c93a-4827-a476-f53e3350382e\",\"wikipedia@search.mozilla.org\":\"69cb4af4-226b-4662-8abb-0375a25e8ba0\",\"bing@search.mozilla.org\":\"22c1bdd1-b50f-42f8-9b42-9b506f50f866\",\"ddg@search.mozilla.org\":\"4ff05fd3-3949-4f5b-a695-336a29770ae7\",\"amazon@search.mozilla.org\":\"46d24c49-8253-4f33-ae83-07d97d11f722\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1667301908);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "20b7523e-43df-44a3-985c-6a46ef2b46ff");
user_pref("toolkit.startup.last_success", 1667301931);
user_pref("toolkit.telemetry.cachedClientID", "f9eb2947-7555-4273-a6c1-c0b9dc4adeef");
user_pref("toolkit.telemetry.previousBuildID", "20221025212237");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
